name: Run AWS Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install AWS dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r tests/requirements-aws-test.txt
          pip install -e .

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: "fake"
          AWS_SECRET_ACCESS_KEY: "fake"
          AWS_DEFAULT_REGION: "eu-central-1"
        run: |
          env | grep AWS
          aws sts get-caller-identity || echo "No credentials available"
          source .venv/bin/activate
          pytest --maxfail=5 --disable-warnings tests/aws/
